-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 11:08:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema moniref
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moniref
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moniref` DEFAULT CHARACTER SET latin1 ;
USE `moniref` ;

-- -----------------------------------------------------
-- Table `moniref`.`electype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moniref`.`electype` (
  `idElecType` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idElecType`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moniref`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moniref`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `phone` INT(11) NULL DEFAULT NULL,
  `Tarifa` FLOAT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `Phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moniref`.`apliance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moniref`.`apliance` (
  `idApliance` INT(11) NOT NULL AUTO_INCREMENT,
  `elecType_idElecType` INT(11) NULL DEFAULT NULL,
  `Marca` VARCHAR(45) NULL DEFAULT NULL,
  `Modelo` VARCHAR(45) NULL DEFAULT NULL,
  `user_idUser` INT(11) NOT NULL,
  PRIMARY KEY (`idApliance`, `user_idUser`),
  INDEX `fk_electrodomestico_elecType1_idx` (`elecType_idElecType` ASC),
  INDEX `fk_apliance_user1_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_electrodomestico_elecType1`
    FOREIGN KEY (`elecType_idElecType`)
    REFERENCES `moniref`.`electype` (`idElecType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apliance_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `moniref`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moniref`.`consumptionregistry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moniref`.`consumptionregistry` (
  `idConsumption` INT(11) NOT NULL AUTO_INCREMENT,
  `apliance_idApliance` INT(11) NOT NULL,
  `watts` DOUBLE NOT NULL,
  `amps` DOUBLE NOT NULL,
  `volts` DOUBLE NOT NULL,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idConsumption`),
  INDEX `fk_Consumos_electrodomestico1_idx` (`apliance_idApliance` ASC),
  CONSTRAINT `fk_Consumos_electrodomestico1`
    FOREIGN KEY (`apliance_idApliance`)
    REFERENCES `moniref`.`apliance` (`idApliance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moniref`.`proto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moniref`.`proto` (
  `idProto` INT(11) NOT NULL,
  `user_idUser` INT(11) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProto`),
  INDEX `fk_dispositivo_usuario1_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_dispositivo_usuario1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `moniref`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moniref`.`proto_has_apliance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moniref`.`proto_has_apliance` (
  `Proto_idProto` INT(11) NOT NULL AUTO_INCREMENT,
  `apliance_idApliance` INT(11) NOT NULL,
  `connectionDate` DATE NULL DEFAULT NULL,
  `disconnectionDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Proto_idProto`, `apliance_idApliance`),
  INDEX `fk_Proto_has_apliance_apliance1_idx` (`apliance_idApliance` ASC),
  INDEX `fk_Proto_has_apliance_Proto1_idx` (`Proto_idProto` ASC),
  CONSTRAINT `fk_Proto_has_apliance_Proto1`
    FOREIGN KEY (`Proto_idProto`)
    REFERENCES `moniref`.`proto` (`idProto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proto_has_apliance_apliance1`
    FOREIGN KEY (`apliance_idApliance`)
    REFERENCES `moniref`.`apliance` (`idApliance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2147483647
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
