-- MySQL Script generated by MySQL Workbench
-- mié 08 nov 2017 10:41:28 MST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  `phone` INT NULL,
  `Tarifa` FLOAT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `Phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`elecType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`elecType` (
  `idElecType` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idElecType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apliance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apliance` (
  `idApliance` INT NOT NULL,
  `elecType_idElecType` INT NULL,
  `Marca` VARCHAR(45) NULL,
  `Modelo` VARCHAR(45) NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`idApliance`),
  INDEX `fk_electrodomestico_elecType1_idx` (`elecType_idElecType` ASC),
  INDEX `fk_apliance_User1_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_electrodomestico_elecType1`
    FOREIGN KEY (`elecType_idElecType`)
    REFERENCES `mydb`.`elecType` (`idElecType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apliance_User1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proto` (
  `idProto` INT NOT NULL,
  `user_idUser` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idProto`),
  INDEX `fk_dispositivo_usuario1_idx` (`user_idUser` ASC),
  CONSTRAINT `fk_dispositivo_usuario1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ConsumptionRegistry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ConsumptionRegistry` (
  `idConsumption` INT NOT NULL,
  `apliance_idApliance` INT NOT NULL,
  `watts` DOUBLE NOT NULL,
  `amps` DOUBLE NOT NULL,
  `volts` DOUBLE NOT NULL,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idConsumption`),
  INDEX `fk_Consumos_electrodomestico1_idx` (`apliance_idApliance` ASC),
  CONSTRAINT `fk_Consumos_electrodomestico1`
    FOREIGN KEY (`apliance_idApliance`)
    REFERENCES `mydb`.`apliance` (`idApliance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proto_has_apliance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proto_has_apliance` (
  `Proto_idProto` INT NOT NULL,
  `apliance_idApliance` INT NOT NULL,
  `connectionDate` DATE NULL,
  `disconnectionDate` DATE NULL,
  PRIMARY KEY (`Proto_idProto`, `apliance_idApliance`),
  INDEX `fk_Proto_has_apliance_apliance1_idx` (`apliance_idApliance` ASC),
  INDEX `fk_Proto_has_apliance_Proto1_idx` (`Proto_idProto` ASC),
  CONSTRAINT `fk_Proto_has_apliance_Proto1`
    FOREIGN KEY (`Proto_idProto`)
    REFERENCES `mydb`.`Proto` (`idProto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proto_has_apliance_apliance1`
    FOREIGN KEY (`apliance_idApliance`)
    REFERENCES `mydb`.`apliance` (`idApliance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
